# Generated by Django 3.2.4 on 2021-06-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStationsStatic',
            fields=[
                ('stop_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=150)),
                ('stop_lat', models.DecimalField(decimal_places=13, max_digits=17)),
                ('stop_long', models.DecimalField(decimal_places=13, max_digits=17)),
            ],
        ),
    ]
