# Generated by Django 3.2.4 on 2021-06-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_routesstatic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripsStatic',
            fields=[
                ('route_id', models.CharField(max_length=15)),
                ('service_id', models.CharField(max_length=15)),
                ('trip_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('shape_id', models.CharField(max_length=50)),
                ('trip_headsign', models.CharField(max_length=50)),
                ('direction_id', models.IntegerField()),
            ],
        ),
    ]
