# Generated by Django 3.2.4 on 2021-06-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tripsstatic'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTimesStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=50)),
                ('arrival_time', models.CharField(max_length=10)),
                ('departure_time', models.CharField(max_length=10)),
                ('stop_id', models.CharField(max_length=15)),
                ('stop_sequence', models.IntegerField()),
                ('stop_headsign', models.CharField(max_length=50)),
                ('pickup_type', models.IntegerField()),
                ('drop_off_type', models.IntegerField()),
                ('shape_dist_travelled', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
    ]
