# Generated by Django 3.2.4 on 2021-06-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stoptimesstatic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoptimesstatic',
            old_name='shape_dist_travelled',
            new_name='shape_dist_traveled',
        ),
    ]
