# Generated by Django 3.2.4 on 2021-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_calendarstatic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDatesStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=8)),
                ('exception_type', models.IntegerField()),
            ],
        ),
    ]
