# Generated by Django 3.2.4 on 2021-06-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_calendardatesstatic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=15)),
                ('agency_name', models.CharField(max_length=50)),
                ('agency_url', models.CharField(max_length=50)),
                ('agency_timezone', models.CharField(max_length=50)),
                ('agency_lang', models.CharField(max_length=15)),
            ],
        ),
    ]
