# Generated by Django 3.2.4 on 2021-06-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_agencystatic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapesStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=20)),
                ('shape_pt_lat', models.DecimalField(decimal_places=13, max_digits=17)),
                ('shape_pt_lon', models.DecimalField(decimal_places=13, max_digits=17)),
                ('shape_pt_sequence', models.IntegerField()),
                ('shape_dist_traveled', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
    ]
