# Generated by Django 3.2.4 on 2021-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shapesstatic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfersStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_id', models.CharField(max_length=15)),
                ('to_stop_id', models.CharField(max_length=15)),
                ('transfer_type', models.IntegerField()),
                ('min_transfer_time', models.IntegerField()),
            ],
        ),
    ]
